#%RAML 1.0
title: Hello

/hello:
  get:
    queryParameters:
      name: string
    responses:
      200:
        body:
          application/json:
            type: string
            example:
              "Hello User"